---
# - name: Debug hostvars
#   debug:
#     msg: "{{ hostvars[item] }}"
#   loop: "{{ groups['apps'] }}"

# - name: fail after debug
#   fail: 

- name: Install HAProxy support packages
  package:
    name: 
      #- httpie
      - haproxy
    state: present
- name: enable HAProxy
  service:
    name: haproxy
    state: started
    enabled: yes
- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart HAproxy


