  - name: install postgres
    yum:
      name: postgresql-server
      state: present
  - name: initialize Postgres
    become: yes
    become_user: postgres
    command: postgresql-setup initdb
    args:
      creates: /var/lib/pgsql/data
  - name: start postgres
    service:
      name: postgresql
      state: started
      enabled: yes 
